### ISSUE TITLE
Eraser often erases somewhere else then where the cursor is

### ISSUE THREAD

**Issue by MelchiorUU** [micrology/prsm#97] opened 2021-10-01 12:53 UTC
When I try to use the eraser it often erases things that are not at the location of my cursor. At the same time the things at my cursor do not get erased. 

I have the same behaviour on Firefox 92.0 (64-bit) and Edge Version 92.0.902.78 (Official build) (64-bit).

**Comment by micrology** [comment] 2021-10-02 12:55
Thank you for this report.  Another user has reported the same, but so far I have been unable to reproduce it.  I will have another go.

**Comment by MelchiorUU** [comment] 2021-10-02 14:54
It seems to be more prevalent when you try to erase larger area’s after each other. Almost as if moving the cursor during erasing somehow gives it an offset.

**Comment by micrology** [comment] 2021-10-02 20:14
I have had another attempt to reproduce this bug, but without success.  The eraser works just as expected for me.  Would you be able to help by sending me an example that I can follow to reproduce the bug?

**Comment by MelchiorUU** [comment] 2021-10-04 12:28
I found one additional “feature” of the bug.

It appears to be an offset between the cursor x,y and where the eraser starts to erase (a different x,y). I do notice that in the top left the offset is 0 and getting larger horizontally if I go the right and larger vertically if I go down. Thus I assume that in the used (x,y) coordinate system the top left is (0,0) and bottom right is (max, max). So there might be some multiplication going on that explains the increasing offset.

**Comment by MelchiorUU** [comment] 2021-10-04 12:38
Tried to recreate the issue by starting fresh “session”. Tried this on Firefox 92.0.1 64-bit on windows 10.

Start session, name board, enable eshow drawing layer to enable drawing gui.

Try to draw anything (line, brush, pencil) and I experience the same offset. But: the drawn line appears, when releasing the mouse button, where my mouse was originally. The “example line” while drawing is somewhere else though. So the “preview” of your drawing has the offset, but the resulting line doesn’t.

**Comment by micrology** [comment] 2021-10-04 15:37
Thanks for the instructions.  I have now been able to reproduce this - by using Windows 10 and Firefox (it behaves the same on Edge).  Drawing works properly and as expected on Mac OS (which I use for development) but incorrectly on Windows.  Now I know how to reproduce the problem, I can work out a solution.

**Comment by micrology** [comment] 2021-10-05 21:22
This bug should now be fixed in the current version, 1.8.0

**Closed by micrology** 2021-10-05 21:22 UTC
